### ISSUE TITLE
Broken with PTR/Mistlands

### ISSUE THREAD

**Issue by cafeoh** [jwlei/EZBuild#2]
It seems methods have been changed around in the latest update (haven't tried this mod on latest stable).

 `Player.QueueUnequipItem` seems to be deprecated and is throwing a `MissingMethodException` on call. I tried tracking what change causes this but unfortunately I've never touched Valheim modding (or C#) and I couldn't find any reference to the Player class.

![valheim_2022-11-29_16-29-46](https://user-images.githubusercontent.com/6636915/204573454-e1977ced-35cb-43f3-b409-ca87a9c8364e.png)

**Comment by jwlei** [comment]
They have changed a bunch in their codebase, I will try to update the mod for mistlands.

**Comment by jwlei** [comment]
Fixed as of 2.0.0
